
let ru = [
	"Главная",
	"О нас",
	"Особенности игры",
	"Системные требования",
	"Отзывы",
	"Рус",
	"ВЫЖИТЬ ЛЮБОЙ ЦЕНОЙ",
	"Испытайте новую социальную королевскую битву",
	"Купить сейчас в Steam",
	"История",
	"Что такое СОС?",
	"социальная королевская битва",
	"Каждый раунд, ",
	" и ",
	"других участников соревнуются, чтобы сбежать со смертельно опасного острова, наполненного монстрами. Хитрость заключается в следующем: ",
	"люди могут выжить. Будете ли вы бежать в одиночку или подружитесь с другими, чтобы сбежать?",
	"ты",
	"15 ",
	"три",
	"Принятие правильных решений может стать разницей между жизнью и смертью.",
	"Что такого особенного?",
	"функции",
	"ВЫЖИТЬ ЛЮБОЙ ЦЕНОЙ",
	"У вас есть 30 минут, чтобы найти реликвию, подать сигнал на эвакуацию и захватить одно из трех мест на спасательном вертолете.",
	"СОЗДАВАЙТЕ СОЮЗНИКОВ И ВРАГОВ",
	"Вы можете добавлять своих друзей и играть вместе, а также создавать врагов, чтобы побеждать и получать больше очков навыков.",
	"ВПЕЧАТЛИТЬ ЗРИТЕЛЯ",
	"А так же вы можете сделать этот проект более популярным, просто сделайте репост и подпишитесь на нас",
	"Может ли мой компьютер запустить эту игру?",
	"Системные Требования",
	"ОС:",
	"Windows 7 64-bit только (В настоящее время нет поддержки OSX)",
	"Процессор:",
	"Intel Core 2 Duo @ 2.4 GHZ or AMD Athlon X2 @ 2.8 GHZ",
	"Память:",
	"8 GB RAM",
	"Место на диске:",
	"8 GB",
	"Графика:",
	"NVIDIA GeForce GTX 660 2GB или AMD Radeon HD 7850 2GB DirectX11 (Шейдерная модель 5)",
	"Что думают люди?",
	"Цитаты из прессы",
	"Наша цель — создать продукт и услугу, которыми вы будете довольны и будете пользоваться ими каждый день. Вот почему мы постоянно работаем над нашими услугами, чтобы сделать их лучше каждый день, и действительно прислушиваемся к тому, что говорят наши пользователи.",
	"Читать больше отзывов",
	"Эван Лахти",
	"Геймер",
	"“Один из моих игровых моментов года.”",
	"Октябрь 18, 2018",
	"Джада Гриффин",
	"Нерд реактор",
	"“Следующая большая вещь в мире стриминга и игр на выживание.”",
	"Декабрь 21, 2018",
	"Аарон Уильямс",
	"Упрокс",
	"“Снуп Догг, играющий дико интересную «SOS», — это смешно.”",
	"Декабрь 24, 2018",
	"Хотите оставаться на связи?",
	"ПОДПИСАТЬСЯ НА НОВОСТИ",
	"Для того, чтобы начать получать наши новости, все, что вам нужно сделать, это ввести свой адрес электронной почты. Обо всем остальном позаботимся мы. Мы будем отправлять вам электронные письма, содержащие информацию об игре. Мы не спамим.",
	"Ваш электронный адрес",
	"Подпишись сейчас",
	"Главная",
	"О нас",
	"Особенности игры",
	"Системные требования",
	"Отзывы",
	"© Outpost Games, Inc., 2018. Все права защищены.",
	"Политика Конфиденциальности",
	"Условия предоставления услуг",
	"Нормы поведения",
];

let fr = [
	"Maison",
	"À propos de nous",
	"Caractéristiques de jeu",
	"Configuration requise",
	"Commentaires",
	"Fra",
	"SURVIVRE À TOUT PRIX",
	"Découvrez la nouvelle bataille royale sociale",
	"Acheter maintenant sur Steam",
	"Histoire",
	"Qu'est-ce que SOS ?",
	"bataille royale sociale",
	"Chaque tour, ",
	" Et ",
	"d'autres concurrents s'affrontent pour échapper à une île mortelle infestée de monstres. L'astuce est celle-ci: ",
	"les gens peuvent survivre. Allez-vous courir seul ou vous lier d'amitié avec d'autres pour vous échapper?",
	"Toi",
	"15 ",
	"trois ",
	"Prendre les bonnes décisions peut faire la différence entre la vie et la mort.",
	"Qu'y a-t-il de si spécial?",
	"les fonctions",
	"SURVIVRE À TOUT PRIX", // here!!!
	"Vous avez 30 minutes pour trouver la relique, signaler une évacuation et sécuriser l'un des trois emplacements dans l'hélicoptère de sauvetage.",
	"CONSTRUISEZ DES ALLIÉS ET DES ENNEMIS",
	"Vous pouvez ajouter vos amis et jouer ensemble, et créer des ennemis pour gagner et obtenir plus de points de compétence.",
	"IMPRESSIONNER LE SPECTATEUR",
	"Et vous pouvez aussi rendre ce projet plus populaire, il suffit de le republier et de vous abonner à nous",
	"Mon ordinateur peut-il exécuter ce jeu?",
	"Configuration requise",
	"SE:",
	"Windows 7 64-bit uniquement (actuellement pas de support OSX)",
	"CPU:",
	"Intel Core 2 Duo @ 2.4 GHZ or AMD Athlon X2 @ 2.8 GHZ",
	"Mémoire:",
	"8 GB RAM",
	"Espace disque:",
	"8 GB",
	"Arts graphiques:",
	"NVIDIA GeForce GTX 660 2GB ou AMD Radeon HD 7850 2GB DirectX11 (Shader modèle 5)",
	"Qu'est-ce que les gens pensent?",
	"Citations de presse",
	"Notre objectif est de créer un produit et un service dont vous serez satisfait et que vous utiliserez tous les jours. C'est pourquoi nous travaillons constamment sur nos services pour les améliorer chaque jour et écoutons vraiment ce que nos utilisateurs ont à dire.",
	"Lire plus d'avis",
	"Evan Lahti",
	"joueur",
	"“Un de mes moments de jeu de l'année.”",
	"Octobre 18, 2018",
	"Jada Griffon",
	"Réacteur nerd",
	"“La prochaine grande nouveauté dans le monde du streaming et des jeux de survie.”",
	"Décembre 21, 2018",
	"Aaron Williams",
	"Uprox",
	"“Snoop Dogg jouant le 'SOS' extrêmement intéressant est ridicule.”",
	"Décembre 24, 2018",
	"Vous voulez rester connecté ?",
	"ABONNEZ-VOUS À LA NEWSLETTER",
	"Pour commencer à recevoir nos actualités, il vous suffit de saisir votre adresse e-mail. Nous nous occuperons de tout le reste. Nous vous enverrons des e-mails contenant des informations sur le jeu. Nous ne spammons pas.",
	"Votre adresse e-mail",
	"Abonnez-vous maintenant",
	"Maison",
	"À propos de nous",
	"Caractéristiques de jeu",
	"Configuration requise",
	"Commentaires",
	"© 2018 Outpost Games, Inc. Tous droits réservés.",
	"Politique de confidentialité",
	"Conditions d'utilisation",
	"Code de conduite",
];
let en = [
	"main",
	"about",
	"game features",
	"SYSTEM REQUIREMENTS",
	"QUOTES",
	"eng",
	"SURVIVE AT ALL COSTS",
	"EXPERIENCE NEW SOCIAL BATTLE ROYALE GAME",
	"Buy on the Steam",
	"THE STORY",
	"WHAT IS SOS?",
	"SOCIAL BATTLE ROYALE GAME",
	"Each round, ",
	" and ",
	"other contestants compete to escape a deadly island filled with monsters. The trick is: ",
	"people can survive. Will you run solo or form friendships with others to escape?",
	"you",
	"15 ",
	"three",
	"Making the right decisions could be the difference between life and death.",
	"WHAT’S SO SPECIAL?",
	"FEATURES",
	"SURVIVE AT ALL COSTS",
	"You have 30 minutes to find a relic, signal for extraction, and grab one of three spots on the rescue chopper.",
	"CREATE ALLIES AND ENEMIES",
	"You can add your friends and play together, and create enemies to win and get more skill points.",
	"IMPRESS THE AUDIENCE",
	"And also you can make this project more popular, just repost and subscribe to us",
	"CAN MY COMPUTER RUN THIS GAME?",
	"SYSTEM REQUIREMENTS",
	"ОС:",
	"Windows 7 64-bit только (No OSX support at this time)",
	"pROCESSOR:",
	"Intel Core 2 Duo @ 2.4 GHZ or AMD Athlon X2 @ 2.8 GHZ",
	"mEMORY:",
	"8 GB RAM",
	"storage:",
	"8 GB",
	"GRAPHICS:",
	"NVIDIA GeForce GTX 660 2GB or AMD Radeon HD 7850 2GB DirectX11 (Shader Model 5)",
	"WHAT PEOPLE THINK?",
	"PRESS QUOTES",
	"Our goal is to create a product and service that you’re satisfied with and use it every day. This is why we’re constantly working on our services to make it better every day and really listen to what our users has to say.",
	"Read more testimonials",
	"Evan Lahti",
	"PC Gamer",
	"“One of my gaming highlights of the year.”",
	"October 18, 2018",
	"Jada Griffin",
	"Nerdreactor",
	"“The next big thing in the world of streaming and survival games.”",
	"December  21, 2018",
	"Aaron Williams",
	"Uproxx",
	"“Snoop Dogg Playing The Wildly Entertaining ‘SOS’ Is Ridiculous.”",
	"December 24, 2018",
	"WANT TO STAY IN TOUCH?",
	"NEWSLETTER SUBSCRIBE",
	"In order to start receiving our news, all you have to do is enter your email address. Everything else will be taken care of by us. We will send you emails containing information about game. We don’t spam.",
	"Your email address",
	"Subscribe now",
	"main",
	"about",
	"game features",
	"SYSTEM REQUIREMENTS",
	"QUOTES",
	"© 2018 Outpost Games, Inc. All Rights Reserved.",
	"PRIVACY POLICY",
	"TERMS OF SERVICES",
	"CODE OF CONDUCT",
]
export {ru, fr, en} 
